//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accommodation
    {
        public Accommodation()
        {
            this.StudentAccommodations = new HashSet<StudentAccommodation>();
        }
    
        public int AccomodationID { get; set; }
        public int AccommodationTypePL { get; set; }
        public string Accommodation1 { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual PickListDetails_Bak PickListDetails_Bak { get; set; }
        public virtual ICollection<StudentAccommodation> StudentAccommodations { get; set; }
    }
}
