//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int AssignmentID { get; set; }
        public string AssignmentName { get; set; }
        public int CategoryPL { get; set; }
        public decimal MaxPoints { get; set; }
        public System.DateTime AssignedDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<bool> MissingGradeCount { get; set; }
        public Nullable<decimal> AssignmentWeight { get; set; }
        public Nullable<bool> IsIncludeInFinalGrade { get; set; }
        public Nullable<int> SchoolCourseSectionID { get; set; }
        public string DocumentExtension { get; set; }
        public string DocumentSize { get; set; }
        public string DocumentType { get; set; }
        public string DocumentName { get; set; }
        public byte[] DocumentData { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
