//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BellSchedule
    {
        public BellSchedule()
        {
            this.BellScheduleDays = new HashSet<BellScheduleDay>();
            this.BellScheduleGrades = new HashSet<BellScheduleGrade>();
            this.BellSchedulePeriods = new HashSet<BellSchedulePeriod>();
        }
    
        public int BellScheduleID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> SchoolYearID { get; set; }
        public Nullable<int> SchoolPeriodID { get; set; }
        public Nullable<int> GradePL { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
        public string BellScheduleName { get; set; }
        public string BellScheduleDescription { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual School School { get; set; }
        public virtual SchoolYear SchoolYear { get; set; }
        public virtual ICollection<BellScheduleDay> BellScheduleDays { get; set; }
        public virtual ICollection<BellScheduleGrade> BellScheduleGrades { get; set; }
        public virtual ICollection<BellSchedulePeriod> BellSchedulePeriods { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak { get; set; }
    }
}
