//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrightspaceStaffSession
    {
        public Nullable<int> SessionID { get; set; }
        public string OrgDefinedID { get; set; }
        public string RoleName { get; set; }
        public Nullable<System.DateTime> SessionStart { get; set; }
        public Nullable<System.DateTime> SessionEnd { get; set; }
        public Nullable<int> ActiveSessionDuration { get; set; }
        public Nullable<int> TotalSessionDuration { get; set; }
        public string IsImpersonation { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> LastActivityTime { get; set; }
        public Nullable<System.DateTime> UserLastActivityTime { get; set; }
        public string TimedOut { get; set; }
        public Nullable<System.DateTime> SessionStartUTC { get; set; }
        public Nullable<System.DateTime> SessionEndUTC { get; set; }
        public Nullable<System.DateTime> LastActivityTimeUTC { get; set; }
        public Nullable<System.DateTime> UserLastActivityTimeUTC { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
