//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingAllotment
    {
        public int BuildingAllotmentID { get; set; }
        public int SchoolID { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public Nullable<short> GradeID { get; set; }
        public Nullable<short> RoomNumber { get; set; }
        public Nullable<short> FloorNumber { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
