//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bulletin
    {
        public Bulletin()
        {
            this.BulletinReads = new HashSet<BulletinRead>();
            this.SchoolBulletins = new HashSet<SchoolBulletin>();
        }
    
        public int BulletinID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<short> Type { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public Nullable<bool> IsChild { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<short> CreationType { get; set; }
    
        public virtual ICollection<BulletinRead> BulletinReads { get; set; }
        public virtual ICollection<SchoolBulletin> SchoolBulletins { get; set; }
    }
}
