//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassAssignmentDocument
    {
        public int ClassAssignmetDocumentID { get; set; }
        public int SchoolCourseSectionID { get; set; }
        public int ClassAssignmentID { get; set; }
        public Nullable<int> PickListCategoryID { get; set; }
        public Nullable<short> GradeScaleID { get; set; }
        public string DocumentName { get; set; }
        public string FilePath { get; set; }
        public string DocmentFile { get; set; }
        public bool IsStudentViewable { get; set; }
        public bool IsActive { get; set; }
        public int CareatedBy { get; set; }
        public System.DateTime CareatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
