//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassAssignment
    {
        public int ClassAssignmentID { get; set; }
        public int SchoolCourseSectionID { get; set; }
        public int GradeMethodID { get; set; }
        public Nullable<int> CopiedFromId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> GradePeriodId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> LabelId { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<short> MaxPoints { get; set; }
        public Nullable<short> Multiplier { get; set; }
        public string ClassAssignmentName { get; set; }
        public string SemesterExam { get; set; }
        public string MidTerm { get; set; }
        public string Final { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public bool IncludeInPeriodGrade { get; set; }
        public bool IncludeInTermGrade { get; set; }
        public bool IncludeInFinalGrade { get; set; }
        public bool IsActive { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifieidDate { get; set; }
    }
}
