//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassGrade
    {
        public int ClassGradeID { get; set; }
        public int ClassAssignmentID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> NoteID { get; set; }
        public Nullable<decimal> Score { get; set; }
        public string GradeComment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifieidDate { get; set; }
    }
}
