//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictGradeScale
    {
        public DistrictGradeScale()
        {
            this.DistrictGradeScaleDetails = new HashSet<DistrictGradeScaleDetail>();
            this.SchoolGradeScales = new HashSet<SchoolGradeScale>();
        }
    
        public int DistrictGradeScaleID { get; set; }
        public int DistrictID { get; set; }
        public string GradeScaleName { get; set; }
        public Nullable<bool> CanEditAtSchool { get; set; }
        public Nullable<bool> Default { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string LegacyDistrictID { get; set; }
    
        public virtual District District { get; set; }
        public virtual ICollection<DistrictGradeScaleDetail> DistrictGradeScaleDetails { get; set; }
        public virtual ICollection<SchoolGradeScale> SchoolGradeScales { get; set; }
    }
}
