//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictContact
    {
        public int DistrictID { get; set; }
        public int EntityContactID { get; set; }
        public int PersonID { get; set; }
        public int ContactTypePL { get; set; }
    }
}
