//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictCourse
    {
        public DistrictCourse()
        {
            this.DistrictCourseHistories = new HashSet<DistrictCourseHistory>();
            this.SchoolCourses = new HashSet<SchoolCourse>();
        }
    
        public int DistrictCourseID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> SchoolYearID { get; set; }
        public Nullable<int> GradeScaleID { get; set; }
        public Nullable<int> CreditFlexPL { get; set; }
        public Nullable<int> CourseLevelPL { get; set; }
        public Nullable<int> CoreAreaCodePL { get; set; }
        public Nullable<int> CTECollegeCreditPL { get; set; }
        public Nullable<int> DepartmentPL { get; set; }
        public Nullable<int> EducationOptionPL { get; set; }
        public Nullable<int> LanguageUsedPL { get; set; }
        public Nullable<int> StudentPopulationPL { get; set; }
        public Nullable<int> SemesterCodePL { get; set; }
        public Nullable<int> StateSubjectCodePL { get; set; }
        public Nullable<int> SubjectAreaForCreditPL { get; set; }
        public Nullable<int> SuggestedMinimumGradeLevelPL { get; set; }
        public Nullable<int> TermLengthPL { get; set; }
        public Nullable<int> DeliveryMethodsPL { get; set; }
        public Nullable<int> CurriculumTypePL { get; set; }
        public Nullable<decimal> CreditHours { get; set; }
        public Nullable<decimal> GPAAddedValue { get; set; }
        public Nullable<short> MaximumEnrollment { get; set; }
        public Nullable<short> MaxTimeForCredit { get; set; }
        public Nullable<short> LengthOfInstruction { get; set; }
        public string SchoolIds { get; set; }
        public string LocationIRN { get; set; }
        public string CourseNumber { get; set; }
        public string CourseName { get; set; }
        public Nullable<bool> IsAttendance { get; set; }
        public Nullable<bool> IsRequiredFinalGrade { get; set; }
        public Nullable<bool> IsHighSchoolCredit { get; set; }
        public Nullable<bool> IsGPA { get; set; }
        public Nullable<bool> IsClassRank { get; set; }
        public Nullable<bool> HonorRoll { get; set; }
        public Nullable<bool> IsPrintonTranscript { get; set; }
        public Nullable<bool> IsPrintOnReportCard { get; set; }
        public Nullable<bool> IsPortal { get; set; }
        public Nullable<bool> IsHomeroomCourse { get; set; }
        public Nullable<bool> IsLunchCourse { get; set; }
        public Nullable<bool> IsStudyHallCourse { get; set; }
        public Nullable<bool> RosterVerification { get; set; }
        public Nullable<bool> IsStateReporting { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string GradeScaleName { get; set; }
        public Nullable<int> SchoolYearPL { get; set; }
        public Nullable<int> Stg_districtCourseID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual District District { get; set; }
        public virtual ICollection<DistrictCourseHistory> DistrictCourseHistories { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak1 { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak2 { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak3 { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak4 { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak5 { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak6 { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak7 { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak8 { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak9 { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak10 { get; set; }
        public virtual ICollection<SchoolCourse> SchoolCourses { get; set; }
    }
}
