//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictOrganizational
    {
        public int DistrictOrganizationalID { get; set; }
        public Nullable<int> AttributeNamePL { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> SchoolYearPL { get; set; }
        public Nullable<int> AttributeTypePL { get; set; }
        public string AttributeText { get; set; }
        public string AttributeNumber { get; set; }
        public Nullable<System.DateTime> AttributeDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual District District { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak1 { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak2 { get; set; }
    }
}
