//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictAddress
    {
        public int AddressID { get; set; }
        public int DistrictID { get; set; }
        public int DistrictAddressID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual District District { get; set; }
    }
}
