//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.DistrictAddresses = new HashSet<DistrictAddress>();
            this.DistrictApplicationSetups = new HashSet<DistrictApplicationSetup>();
            this.DistrictAreas = new HashSet<DistrictArea>();
            this.DistrictAssessments = new HashSet<DistrictAssessment>();
            this.DistrictAttendancePatterns = new HashSet<DistrictAttendancePattern>();
            this.DistrictCourses = new HashSet<DistrictCourse>();
            this.DistrictGPASetups = new HashSet<DistrictGPASetup>();
            this.DistrictGradeScales = new HashSet<DistrictGradeScale>();
            this.DistrictOrganizationals = new HashSet<DistrictOrganizational>();
            this.DistrictPhones = new HashSet<DistrictPhone>();
            this.DistrictRegions = new HashSet<DistrictRegion>();
            this.EMISReportPeriodDistricts = new HashSet<EMISReportPeriodDistrict>();
            this.Schools = new HashSet<School>();
            this.StaffDistrictMappings = new HashSet<StaffDistrictMapping>();
            this.StudentAssessments = new HashSet<StudentAssessment>();
        }
    
        public int DistrictID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<int> PickListCategoryID { get; set; }
        public Nullable<int> DistrictTypePL { get; set; }
        public string DistrictName { get; set; }
        public string DistrictIRN { get; set; }
        public string DistricShortCode { get; set; }
        public Nullable<double> PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public byte[] DistrictPicture { get; set; }
        public byte[] DistrictLogo { get; set; }
        public Nullable<bool> ActiveStatus { get; set; }
        public Nullable<bool> ExcludeFromStateReporting { get; set; }
        public Nullable<bool> IsEvolveDistrict { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string LegacyDistrictID { get; set; }
        public string LoadSource { get; set; }
        public Nullable<int> STG_TableID { get; set; }
        public string RecordseMail { get; set; }
    
        public virtual ICollection<DistrictAddress> DistrictAddresses { get; set; }
        public virtual ICollection<DistrictApplicationSetup> DistrictApplicationSetups { get; set; }
        public virtual ICollection<DistrictArea> DistrictAreas { get; set; }
        public virtual ICollection<DistrictAssessment> DistrictAssessments { get; set; }
        public virtual ICollection<DistrictAttendancePattern> DistrictAttendancePatterns { get; set; }
        public virtual ICollection<DistrictCourse> DistrictCourses { get; set; }
        public virtual ICollection<DistrictGPASetup> DistrictGPASetups { get; set; }
        public virtual ICollection<DistrictGradeScale> DistrictGradeScales { get; set; }
        public virtual ICollection<DistrictOrganizational> DistrictOrganizationals { get; set; }
        public virtual ICollection<DistrictPhone> DistrictPhones { get; set; }
        public virtual ICollection<DistrictRegion> DistrictRegions { get; set; }
        public virtual ICollection<EMISReportPeriodDistrict> EMISReportPeriodDistricts { get; set; }
        public virtual PickListCategory_Bak PickListCategory_Bak { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak { get; set; }
        public virtual ICollection<School> Schools { get; set; }
        public virtual ICollection<StaffDistrictMapping> StaffDistrictMappings { get; set; }
        public virtual ICollection<StudentAssessment> StudentAssessments { get; set; }
    }
}
