//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictAttendancePattern
    {
        public DistrictAttendancePattern()
        {
            this.DistrictAttendancePatternEvents = new HashSet<DistrictAttendancePatternEvent>();
            this.SchoolAttendancePatterns = new HashSet<SchoolAttendancePattern>();
        }
    
        public int DistrictAttendancePatternID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<decimal> HoursPerDay { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public Nullable<decimal> TotalDays { get; set; }
        public string PatternName { get; set; }
        public string PatternDescription { get; set; }
        public string ScheduledDays { get; set; }
        public string ScheduledGradeLevels { get; set; }
        public Nullable<System.DateTime> PatternsStartDate { get; set; }
        public Nullable<System.DateTime> PatternsEndDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string LegacyDistrictID { get; set; }
        public string LegacySchoolID { get; set; }
        public string LegacyPatternID { get; set; }
        public Nullable<int> SchoolYearPL { get; set; }
    
        public virtual District District { get; set; }
        public virtual ICollection<DistrictAttendancePatternEvent> DistrictAttendancePatternEvents { get; set; }
        public virtual ICollection<SchoolAttendancePattern> SchoolAttendancePatterns { get; set; }
    }
}
