//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMISReportingFormat
    {
        public int ReportingFormatID { get; set; }
        public string ExtractName { get; set; }
        public string RecordFieldNumber { get; set; }
        public string DataElement { get; set; }
        public string Student_S____Opening { get; set; }
        public string Student_S____Middle { get; set; }
        public string Student_S____Year_End { get; set; }
        public string Assessment_A_ { get; set; }
        public string Calendar_C_ { get; set; }
        public string Graduate_G_ { get; set; }
        public string Staff_Course_L__ { get; set; }
        public string March_D_ { get; set; }
        public string Graduate_R_ { get; set; }
        public string E_Transcript_E_ { get; set; }
        public string Exchange_X_ { get; set; }
    }
}
