//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMISReport
    {
        public EMISReport()
        {
            this.EMISReportFields = new HashSet<EMISReportField>();
        }
    
        public int ReportID { get; set; }
        public int ReportPeriodID { get; set; }
        public Nullable<int> SchoolIRN { get; set; }
        public string ReportTypeID { get; set; }
        public string ReportName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual EMISReportPeriodLookup EMISReportPeriodLookup { get; set; }
        public virtual ICollection<EMISReportField> EMISReportFields { get; set; }
    }
}
