//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMISReportPeriod
    {
        public EMISReportPeriod()
        {
            this.EMISReportPeriodDistricts = new HashSet<EMISReportPeriodDistrict>();
        }
    
        public int EMISReportPeriodID { get; set; }
        public int ReportPeriodID { get; set; }
        public string ReportName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SchoolYearPL { get; set; }
    
        public virtual EMISReportPeriodLookup EMISReportPeriodLookup { get; set; }
        public virtual ICollection<EMISReportPeriodDistrict> EMISReportPeriodDistricts { get; set; }
    }
}
