//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int EnrollmentID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> EnrollmentCodePL { get; set; }
        public Nullable<int> AdmittedFromDistrict { get; set; }
        public Nullable<int> DistrictOfResidence { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public Nullable<int> RelationshipTypeCodePL { get; set; }
        public string EnrollmentDescription { get; set; }
        public string DistrictResidenceIRN { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string LegacyStudentID { get; set; }
        public string LegacyAdmittedFromdistrict { get; set; }
        public Nullable<int> STG_Enrollment_ID { get; set; }
        public Nullable<int> FormerSchoolTypePL { get; set; }
        public Nullable<int> FormerSchoolDistrict { get; set; }
        public Nullable<int> FormerSchoolAttended { get; set; }
        public Nullable<int> EnrolledSchoolID { get; set; }
    }
}
