//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentByYear_08162016
    {
        public int EnrollmentByYearID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public int SchoolYearPL { get; set; }
        public Nullable<int> GradeLevelPL { get; set; }
        public Nullable<int> StateGradeLevelPL { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> RetainStatusPL { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string DisadvantagementPL { get; set; }
        public string PreschoolPovertyPL { get; set; }
        public string LimitedEnglishProficiencyPL { get; set; }
        public string RetainedStatusPL { get; set; }
        public string TuitionStatusPL { get; set; }
        public string ImmigrantStatusPL { get; set; }
        public string UnaccompaniedYouthPL { get; set; }
        public string PercentOfTime { get; set; }
        public string DistrictAdmissionDate { get; set; }
        public string AssignedSchoolID { get; set; }
        public string HowReceivedSchoolID { get; set; }
        public string SentToDistrictIRN1 { get; set; }
        public string PercentofTime1 { get; set; }
        public string SentToDistrictIRN2 { get; set; }
        public string PercentofTime2 { get; set; }
        public string HowReceivedCodePL { get; set; }
        public string ForExGradPlanPL { get; set; }
        public string SSID { get; set; }
        public string PlansToAttendDistrict { get; set; }
        public string AttendancePattern { get; set; }
        public string HomeLessPL { get; set; }
        public string Migrant { get; set; }
    }
}
