//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {
        public int ExceptionLogID { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string URL { get; set; }
        public string Message { get; set; }
        public string Source { get; set; }
        public int PersonID { get; set; }
        public int SchoolID { get; set; }
        public string RegistrationNumber { get; set; }
    }
}
