//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForgotPasswordKey
    {
        public int ForgotPasswordKeyID { get; set; }
        public string UserName { get; set; }
        public string PasswordKey { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
