//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeTopicDetail
    {
        public int GradeTopicDetailID { get; set; }
        public Nullable<int> ClassAssignmentID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> TopicID { get; set; }
        public Nullable<decimal> Score { get; set; }
    }
}
