//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradePeriod
    {
        public int GradePeriodID { get; set; }
        public int TermID { get; set; }
        public Nullable<int> SchoolYearTypeGradePeriodID { get; set; }
        public short AllowOverride { get; set; }
        public short TermExam { get; set; }
        public short FinalExam { get; set; }
        public short Active { get; set; }
        public short EndPeriod { get; set; }
        public Nullable<short> SortOrder { get; set; }
        public string GradePeriodName { get; set; }
        public string Period { get; set; }
        public string Code { get; set; }
        public string MidTermPeriod { get; set; }
        public string MidTermCode { get; set; }
        public string Abbreviation { get; set; }
        public string CommentPeriodCode { get; set; }
        public string ImportCode { get; set; }
        public string MideTermCommentCode { get; set; }
        public string ImportStoreCode { get; set; }
        public System.DateTime GradePeriodStartDate { get; set; }
        public Nullable<System.DateTime> GradePeriodEndDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
