//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public int MenuItemsID { get; set; }
        public Nullable<int> MenuTypeID { get; set; }
        public Nullable<int> ParentMenuID { get; set; }
        public Nullable<short> MenuID { get; set; }
        public short MenuOrder { get; set; }
        public string MenuName { get; set; }
        public string MenuDisplayName { get; set; }
        public string MenuURL { get; set; }
        public string ImageURL { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Create { get; set; }
        public Nullable<bool> Read { get; set; }
        public Nullable<bool> Update { get; set; }
        public Nullable<bool> Delete { get; set; }
        public string CreateControl { get; set; }
        public string ReadControl { get; set; }
        public string UpdateControl { get; set; }
        public string DeleteControl { get; set; }
    
        public virtual MenuType MenuType { get; set; }
    }
}
