//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuType
    {
        public MenuType()
        {
            this.MenuItems = new HashSet<MenuItem>();
            this.MenuItems_NEW = new HashSet<MenuItems_NEW>();
        }
    
        public int MenuTypeID { get; set; }
        public string MenuTypeName { get; set; }
        public string MenuTypeDescription { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<MenuItem> MenuItems { get; set; }
        public virtual ICollection<MenuItems_NEW> MenuItems_NEW { get; set; }
    }
}
