//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdysseywareCourseMapping
    {
        public int OdysseywareCourseMappingID { get; set; }
        public string OWCourseID { get; set; }
        public string OWCourseName { get; set; }
        public string OWCourseSubject { get; set; }
        public string CourseNumber { get; set; }
        public string SectionName { get; set; }
        public string SectionNumber { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
