//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orientation
    {
        public Orientation()
        {
            this.OrientationSchedules = new HashSet<OrientationSchedule>();
        }
    
        public int OrientationID { get; set; }
        public int SchoolID { get; set; }
        public Nullable<int> StudentApplicationID { get; set; }
        public Nullable<int> OrientationScheduleID { get; set; }
        public Nullable<int> OrientationStatusPL { get; set; }
        public Nullable<int> OrientationTypePL { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual OrientationSchedule OrientationSchedule { get; set; }
        public virtual School School { get; set; }
        public virtual ICollection<OrientationSchedule> OrientationSchedules { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak { get; set; }
    }
}
