//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrientationSchedule
    {
        public OrientationSchedule()
        {
            this.Orientations = new HashSet<Orientation>();
        }
    
        public int OrientationScheduleID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> CounsellorID { get; set; }
        public Nullable<int> OrientationRegionPL { get; set; }
        public Nullable<int> Location { get; set; }
        public string Room { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> OrientationDate { get; set; }
        public Nullable<System.DateTime> OrientationTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string OrientationRegion { get; set; }
        public string LegacyStudentApplicationID { get; set; }
        public string LegacyStaffID { get; set; }
        public string LegacyCounselorID { get; set; }
        public Nullable<int> OrientationID { get; set; }
    
        public virtual ICollection<Orientation> Orientations { get; set; }
        public virtual Orientation Orientation { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak { get; set; }
    }
}
