//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person07082016
    {
        public int PersonID { get; set; }
        public int RoleID { get; set; }
        public Nullable<int> HispanicPL { get; set; }
        public Nullable<int> MaritalStatusPL { get; set; }
        public string GenderID { get; set; }
        public string PrefixID { get; set; }
        public string SuffixID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string SSN { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public System.DateTime DOB { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Source { get; set; }
        public string LegacyStaffID { get; set; }
        public string LegacySchool { get; set; }
        public string LegacyStudentID { get; set; }
        public string LegacyContactID { get; set; }
        public string NickName { get; set; }
        public bool IsFirstTimeLogin { get; set; }
        public Nullable<int> STG_Person_ID { get; set; }
    }
}
