//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickListDetails_Bak
    {
        public PickListDetails_Bak()
        {
            this.Accommodations = new HashSet<Accommodation>();
            this.Addresses = new HashSet<Address>();
            this.AssessmentAreaAccommodations = new HashSet<AssessmentAreaAccommodation>();
            this.AssessmentAssessmentArea_old = new HashSet<AssessmentAssessmentArea_old>();
            this.AssessmentAssessmentArea_old1 = new HashSet<AssessmentAssessmentArea_old>();
            this.AttendanceSettings = new HashSet<AttendanceSetting>();
            this.AttendanceSettings1 = new HashSet<AttendanceSetting>();
            this.AttendanceSettings2 = new HashSet<AttendanceSetting>();
            this.BellSchedules = new HashSet<BellSchedule>();
            this.BellScheduleGrades = new HashSet<BellScheduleGrade>();
            this.Districts = new HashSet<District>();
            this.DistrictAttendancePatternEvents = new HashSet<DistrictAttendancePatternEvent>();
            this.DistrictCourses = new HashSet<DistrictCourse>();
            this.DistrictCourses1 = new HashSet<DistrictCourse>();
            this.DistrictCourses2 = new HashSet<DistrictCourse>();
            this.DistrictCourses3 = new HashSet<DistrictCourse>();
            this.DistrictCourses4 = new HashSet<DistrictCourse>();
            this.DistrictCourses5 = new HashSet<DistrictCourse>();
            this.DistrictCourses6 = new HashSet<DistrictCourse>();
            this.DistrictCourses7 = new HashSet<DistrictCourse>();
            this.DistrictCourses8 = new HashSet<DistrictCourse>();
            this.DistrictCourses9 = new HashSet<DistrictCourse>();
            this.DistrictCourses10 = new HashSet<DistrictCourse>();
            this.DistrictOrganizationals = new HashSet<DistrictOrganizational>();
            this.DistrictOrganizationals1 = new HashSet<DistrictOrganizational>();
            this.DistrictOrganizationals2 = new HashSet<DistrictOrganizational>();
            this.DistrictPhones = new HashSet<DistrictPhone>();
            this.Orientations = new HashSet<Orientation>();
            this.OrientationSchedules = new HashSet<OrientationSchedule>();
            this.People = new HashSet<Person>();
            this.PersonAddresses = new HashSet<PersonAddress>();
            this.Rooms = new HashSet<Room>();
            this.SchoolAttendancePatternEvents = new HashSet<SchoolAttendancePatternEvent>();
            this.SchoolContacts = new HashSet<SchoolContact>();
            this.SchoolContacts1 = new HashSet<SchoolContact>();
            this.SchoolCourses = new HashSet<SchoolCourse>();
            this.SchoolCourses1 = new HashSet<SchoolCourse>();
            this.SchoolCourses2 = new HashSet<SchoolCourse>();
            this.SchoolCourses3 = new HashSet<SchoolCourse>();
            this.SchoolCourses4 = new HashSet<SchoolCourse>();
            this.SchoolCourses5 = new HashSet<SchoolCourse>();
            this.SchoolCourses6 = new HashSet<SchoolCourse>();
            this.SchoolCourses7 = new HashSet<SchoolCourse>();
            this.SchoolCourseSections = new HashSet<SchoolCourseSection>();
            this.SchoolCourseSections1 = new HashSet<SchoolCourseSection>();
            this.SchoolCourseSections2 = new HashSet<SchoolCourseSection>();
            this.SchoolCourseSections3 = new HashSet<SchoolCourseSection>();
            this.SchoolCourseSections4 = new HashSet<SchoolCourseSection>();
            this.SchoolCourseSections5 = new HashSet<SchoolCourseSection>();
            this.SchoolGradeLevels = new HashSet<SchoolGradeLevel>();
            this.SchoolGradeLevels1 = new HashSet<SchoolGradeLevel>();
            this.SchoolTerms = new HashSet<SchoolTerm>();
            this.SchoolYears = new HashSet<SchoolYear>();
            this.SchoolYearTermTypes = new HashSet<SchoolYearTermType>();
            this.SectionStaffMappings = new HashSet<SectionStaffMapping>();
            this.Staffs = new HashSet<Staff>();
            this.Students = new HashSet<Student>();
            this.Students1 = new HashSet<Student>();
            this.StudentApplications = new HashSet<StudentApplication>();
            this.StudentApplications1 = new HashSet<StudentApplication>();
            this.StudentApplications2 = new HashSet<StudentApplication>();
            this.StudentApplications3 = new HashSet<StudentApplication>();
            this.StudentApplications4 = new HashSet<StudentApplication>();
            this.StudentApplicationContacts = new HashSet<StudentApplicationContact>();
            this.StudentApplicationPhones = new HashSet<StudentApplicationPhone>();
            this.StudentAssessments = new HashSet<StudentAssessment>();
            this.StudentAssessments1 = new HashSet<StudentAssessment>();
            this.StudentAssessments2 = new HashSet<StudentAssessment>();
            this.StudentAssessments3 = new HashSet<StudentAssessment>();
            this.StudentAssessmentAccommodations = new HashSet<StudentAssessmentAccommodation>();
            this.StudentAttendances = new HashSet<StudentAttendance>();
            this.StudentAttendances1 = new HashSet<StudentAttendance>();
            this.StudentDayAttendance_03022016 = new HashSet<StudentDayAttendance_03022016>();
            this.StudentETRs = new HashSet<StudentETR>();
            this.StudentETRs1 = new HashSet<StudentETR>();
            this.StudentETRs2 = new HashSet<StudentETR>();
            this.StudentETRs3 = new HashSet<StudentETR>();
            this.StudentETRs4 = new HashSet<StudentETR>();
            this.StudentExcessiveHabitualAbs = new HashSet<StudentExcessiveHabitualAb>();
            this.StudentExcessiveHabitualAbs1 = new HashSet<StudentExcessiveHabitualAb>();
            this.StudentExcessiveHabitualAbs2 = new HashSet<StudentExcessiveHabitualAb>();
            this.StudentExcessiveHabitualAbs3 = new HashSet<StudentExcessiveHabitualAb>();
            this.StudentExcessiveHabitualAbs4 = new HashSet<StudentExcessiveHabitualAb>();
            this.StudentIEPs = new HashSet<StudentIEP>();
            this.StudentIEPs1 = new HashSet<StudentIEP>();
            this.StudentIEPs2 = new HashSet<StudentIEP>();
            this.StudentIEPs3 = new HashSet<StudentIEP>();
            this.StudentNotes = new HashSet<StudentNote>();
            this.StudentNotes1 = new HashSet<StudentNote>();
            this.StudentNotes2 = new HashSet<StudentNote>();
            this.StudentOrientations = new HashSet<StudentOrientation>();
            this.StudentOrientations1 = new HashSet<StudentOrientation>();
            this.StudentOrientationSchedules = new HashSet<StudentOrientationSchedule>();
            this.StudentPrograms = new HashSet<StudentProgram>();
            this.StudentSchedules = new HashSet<StudentSchedule>();
            this.StudentStandingRecords = new HashSet<StudentStandingRecord>();
            this.StudentStandingRecords1 = new HashSet<StudentStandingRecord>();
            this.StudentStandingRecords2 = new HashSet<StudentStandingRecord>();
            this.StudentStandingRecords3 = new HashSet<StudentStandingRecord>();
            this.SchoolTerms1 = new HashSet<SchoolTerm>();
            this.StudentSchedules1 = new HashSet<StudentSchedule>();
            this.Withdrawals = new HashSet<Withdrawal>();
        }
    
        public int PickListDetailsID { get; set; }
        public Nullable<int> PickListCategoryID { get; set; }
        public Nullable<int> ParentPickListID { get; set; }
        public Nullable<short> CustomSortOrder { get; set; }
        public string ValueDescription { get; set; }
        public string StateReportingElements { get; set; }
        public string StateReportingValue { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> StateReportElement { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ParentPickListDetailID { get; set; }
    
        public virtual ICollection<Accommodation> Accommodations { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<AssessmentAreaAccommodation> AssessmentAreaAccommodations { get; set; }
        public virtual ICollection<AssessmentAssessmentArea_old> AssessmentAssessmentArea_old { get; set; }
        public virtual ICollection<AssessmentAssessmentArea_old> AssessmentAssessmentArea_old1 { get; set; }
        public virtual ICollection<AttendanceSetting> AttendanceSettings { get; set; }
        public virtual ICollection<AttendanceSetting> AttendanceSettings1 { get; set; }
        public virtual ICollection<AttendanceSetting> AttendanceSettings2 { get; set; }
        public virtual ICollection<BellSchedule> BellSchedules { get; set; }
        public virtual ICollection<BellScheduleGrade> BellScheduleGrades { get; set; }
        public virtual ICollection<District> Districts { get; set; }
        public virtual ICollection<DistrictAttendancePatternEvent> DistrictAttendancePatternEvents { get; set; }
        public virtual ICollection<DistrictCourse> DistrictCourses { get; set; }
        public virtual ICollection<DistrictCourse> DistrictCourses1 { get; set; }
        public virtual ICollection<DistrictCourse> DistrictCourses2 { get; set; }
        public virtual ICollection<DistrictCourse> DistrictCourses3 { get; set; }
        public virtual ICollection<DistrictCourse> DistrictCourses4 { get; set; }
        public virtual ICollection<DistrictCourse> DistrictCourses5 { get; set; }
        public virtual ICollection<DistrictCourse> DistrictCourses6 { get; set; }
        public virtual ICollection<DistrictCourse> DistrictCourses7 { get; set; }
        public virtual ICollection<DistrictCourse> DistrictCourses8 { get; set; }
        public virtual ICollection<DistrictCourse> DistrictCourses9 { get; set; }
        public virtual ICollection<DistrictCourse> DistrictCourses10 { get; set; }
        public virtual ICollection<DistrictOrganizational> DistrictOrganizationals { get; set; }
        public virtual ICollection<DistrictOrganizational> DistrictOrganizationals1 { get; set; }
        public virtual ICollection<DistrictOrganizational> DistrictOrganizationals2 { get; set; }
        public virtual ICollection<DistrictPhone> DistrictPhones { get; set; }
        public virtual ICollection<Orientation> Orientations { get; set; }
        public virtual ICollection<OrientationSchedule> OrientationSchedules { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<PersonAddress> PersonAddresses { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual ICollection<SchoolAttendancePatternEvent> SchoolAttendancePatternEvents { get; set; }
        public virtual ICollection<SchoolContact> SchoolContacts { get; set; }
        public virtual ICollection<SchoolContact> SchoolContacts1 { get; set; }
        public virtual ICollection<SchoolCourse> SchoolCourses { get; set; }
        public virtual ICollection<SchoolCourse> SchoolCourses1 { get; set; }
        public virtual ICollection<SchoolCourse> SchoolCourses2 { get; set; }
        public virtual ICollection<SchoolCourse> SchoolCourses3 { get; set; }
        public virtual ICollection<SchoolCourse> SchoolCourses4 { get; set; }
        public virtual ICollection<SchoolCourse> SchoolCourses5 { get; set; }
        public virtual ICollection<SchoolCourse> SchoolCourses6 { get; set; }
        public virtual ICollection<SchoolCourse> SchoolCourses7 { get; set; }
        public virtual ICollection<SchoolCourseSection> SchoolCourseSections { get; set; }
        public virtual ICollection<SchoolCourseSection> SchoolCourseSections1 { get; set; }
        public virtual ICollection<SchoolCourseSection> SchoolCourseSections2 { get; set; }
        public virtual ICollection<SchoolCourseSection> SchoolCourseSections3 { get; set; }
        public virtual ICollection<SchoolCourseSection> SchoolCourseSections4 { get; set; }
        public virtual ICollection<SchoolCourseSection> SchoolCourseSections5 { get; set; }
        public virtual ICollection<SchoolGradeLevel> SchoolGradeLevels { get; set; }
        public virtual ICollection<SchoolGradeLevel> SchoolGradeLevels1 { get; set; }
        public virtual ICollection<SchoolTerm> SchoolTerms { get; set; }
        public virtual ICollection<SchoolYear> SchoolYears { get; set; }
        public virtual ICollection<SchoolYearTermType> SchoolYearTermTypes { get; set; }
        public virtual ICollection<SectionStaffMapping> SectionStaffMappings { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Student> Students1 { get; set; }
        public virtual ICollection<StudentApplication> StudentApplications { get; set; }
        public virtual ICollection<StudentApplication> StudentApplications1 { get; set; }
        public virtual ICollection<StudentApplication> StudentApplications2 { get; set; }
        public virtual ICollection<StudentApplication> StudentApplications3 { get; set; }
        public virtual ICollection<StudentApplication> StudentApplications4 { get; set; }
        public virtual ICollection<StudentApplicationContact> StudentApplicationContacts { get; set; }
        public virtual ICollection<StudentApplicationPhone> StudentApplicationPhones { get; set; }
        public virtual ICollection<StudentAssessment> StudentAssessments { get; set; }
        public virtual ICollection<StudentAssessment> StudentAssessments1 { get; set; }
        public virtual ICollection<StudentAssessment> StudentAssessments2 { get; set; }
        public virtual ICollection<StudentAssessment> StudentAssessments3 { get; set; }
        public virtual ICollection<StudentAssessmentAccommodation> StudentAssessmentAccommodations { get; set; }
        public virtual ICollection<StudentAttendance> StudentAttendances { get; set; }
        public virtual ICollection<StudentAttendance> StudentAttendances1 { get; set; }
        public virtual ICollection<StudentDayAttendance_03022016> StudentDayAttendance_03022016 { get; set; }
        public virtual ICollection<StudentETR> StudentETRs { get; set; }
        public virtual ICollection<StudentETR> StudentETRs1 { get; set; }
        public virtual ICollection<StudentETR> StudentETRs2 { get; set; }
        public virtual ICollection<StudentETR> StudentETRs3 { get; set; }
        public virtual ICollection<StudentETR> StudentETRs4 { get; set; }
        public virtual ICollection<StudentExcessiveHabitualAb> StudentExcessiveHabitualAbs { get; set; }
        public virtual ICollection<StudentExcessiveHabitualAb> StudentExcessiveHabitualAbs1 { get; set; }
        public virtual ICollection<StudentExcessiveHabitualAb> StudentExcessiveHabitualAbs2 { get; set; }
        public virtual ICollection<StudentExcessiveHabitualAb> StudentExcessiveHabitualAbs3 { get; set; }
        public virtual ICollection<StudentExcessiveHabitualAb> StudentExcessiveHabitualAbs4 { get; set; }
        public virtual ICollection<StudentIEP> StudentIEPs { get; set; }
        public virtual ICollection<StudentIEP> StudentIEPs1 { get; set; }
        public virtual ICollection<StudentIEP> StudentIEPs2 { get; set; }
        public virtual ICollection<StudentIEP> StudentIEPs3 { get; set; }
        public virtual ICollection<StudentNote> StudentNotes { get; set; }
        public virtual ICollection<StudentNote> StudentNotes1 { get; set; }
        public virtual ICollection<StudentNote> StudentNotes2 { get; set; }
        public virtual ICollection<StudentOrientation> StudentOrientations { get; set; }
        public virtual ICollection<StudentOrientation> StudentOrientations1 { get; set; }
        public virtual ICollection<StudentOrientationSchedule> StudentOrientationSchedules { get; set; }
        public virtual ICollection<StudentProgram> StudentPrograms { get; set; }
        public virtual ICollection<StudentSchedule> StudentSchedules { get; set; }
        public virtual ICollection<StudentStandingRecord> StudentStandingRecords { get; set; }
        public virtual ICollection<StudentStandingRecord> StudentStandingRecords1 { get; set; }
        public virtual ICollection<StudentStandingRecord> StudentStandingRecords2 { get; set; }
        public virtual ICollection<StudentStandingRecord> StudentStandingRecords3 { get; set; }
        public virtual ICollection<SchoolTerm> SchoolTerms1 { get; set; }
        public virtual ICollection<StudentSchedule> StudentSchedules1 { get; set; }
        public virtual ICollection<Withdrawal> Withdrawals { get; set; }
    }
}
