//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickListDetail
    {
        public int PickListDetailsID { get; set; }
        public Nullable<int> PickListCategoryID { get; set; }
        public Nullable<int> ParentPickListID { get; set; }
        public Nullable<short> CustomSortOrder { get; set; }
        public string ValueDescription { get; set; }
        public string StateReportingElements { get; set; }
        public string StateReportingValue { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> StateReportElement { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ParentPickListDetailID { get; set; }
    }
}
