//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickListCategory_Bak
    {
        public PickListCategory_Bak()
        {
            this.Districts = new HashSet<District>();
            this.PersonDisabilities = new HashSet<PersonDisability>();
        }
    
        public int PickListCategoryID { get; set; }
        public string PickListCategory { get; set; }
        public string SortElement { get; set; }
        public string SortOrder { get; set; }
        public string DefaultPickListID { get; set; }
        public string StateOrCore { get; set; }
        public string PickListDisplay { get; set; }
        public string Constant { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<District> Districts { get; set; }
        public virtual ICollection<PersonDisability> PersonDisabilities { get; set; }
    }
}
