//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortalStudentAddress
    {
        public int PortalStudentAddressID { get; set; }
        public int StudentID { get; set; }
        public int AddressTypePL { get; set; }
        public Nullable<int> CurrentAddressID { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string City { get; set; }
        public string Apartment { get; set; }
        public string Lot { get; set; }
        public string Other { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string Subdivision { get; set; }
        public string PORDocumentExtension { get; set; }
        public string PORDocumentSize { get; set; }
        public string PORDocumentType { get; set; }
        public string PORDocumentName { get; set; }
        public byte[] PORDocumentData { get; set; }
        public Nullable<int> SubmittedBy { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ReviewerId { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public Nullable<int> Approved { get; set; }
        public Nullable<int> RejectedReasonPL { get; set; }
        public Nullable<System.DateTime> CurrentAddressEndDate { get; set; }
        public string EditOrRemoveAddress { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
