//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramCode
    {
        public int ProgramCodeID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> CalendarID { get; set; }
        public string ProgramCode1 { get; set; }
        public string ProgramProviderIRN { get; set; }
        public Nullable<System.DateTime> EnrollmentStartDate { get; set; }
        public Nullable<System.DateTime> EnrollmentEndDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EmployeeID { get; set; }
        public string BuildingIRN { get; set; }
        public string LegacyStudentID { get; set; }
        public string Source { get; set; }
        public Nullable<int> STG_StudentProgram_ID { get; set; }
    
        public virtual School School { get; set; }
        public virtual Student Student { get; set; }
    }
}
