//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequiredDocument
    {
        public int RequiredDocumentID { get; set; }
        public int StudentID { get; set; }
        public string BirthCertificate { get; set; }
        public Nullable<System.DateTime> BirthCertificationSubmitDate { get; set; }
        public string ProofofResidence { get; set; }
        public Nullable<System.DateTime> ProofofResidenceSubmitDate { get; set; }
        public string Immunization { get; set; }
        public Nullable<System.DateTime> ImmuniaztionSubmitDate { get; set; }
        public string Custody { get; set; }
        public Nullable<System.DateTime> CustodySubmitDate { get; set; }
        public string LastGradeCard { get; set; }
        public Nullable<System.DateTime> LastGradeCardSubmitDate { get; set; }
        public string Transcript { get; set; }
        public Nullable<System.DateTime> TranscriptSubmitDate { get; set; }
        public string TestingOGT { get; set; }
        public Nullable<System.DateTime> TestingOGTSubmitDate { get; set; }
        public string TestingOAA { get; set; }
        public Nullable<System.DateTime> TestingOAASubmitDate { get; set; }
        public string TestingPARCC { get; set; }
        public Nullable<System.DateTime> TestingPARCCSubmitDate { get; set; }
        public string TestingACT { get; set; }
        public Nullable<System.DateTime> TestingACTSubmitDate { get; set; }
        public Nullable<System.DateTime> SchoolRequestSentDate { get; set; }
        public Nullable<int> SchoolRequestSentTo { get; set; }
        public Nullable<System.DateTime> RecordRequestReceived { get; set; }
        public Nullable<int> SchoolRequestReceivedFrom { get; set; }
        public Nullable<System.DateTime> RecordSentDate { get; set; }
        public string EmergencyMedical { get; set; }
        public Nullable<System.DateTime> EmergencyMedicalSubmitDate { get; set; }
        public string EnrollmentPolicy { get; set; }
        public Nullable<System.DateTime> EnrollmentPolicySubmitDate { get; set; }
        public string FinancialResponsibilityPolicy { get; set; }
        public Nullable<System.DateTime> FinancialResponsibilityPolicySubmitDate { get; set; }
        public string AcceptableUsePolicy { get; set; }
        public Nullable<System.DateTime> AcceptableUsePolicySubmitDate { get; set; }
        public string PublicityPolicy { get; set; }
        public Nullable<System.DateTime> PublicityPolicySubmitDate { get; set; }
        public string StudentParentContract { get; set; }
        public Nullable<System.DateTime> StudentParentContractSubmitDate { get; set; }
        public string IncomeInformation { get; set; }
        public Nullable<System.DateTime> IncomeInformationSubmitDate { get; set; }
        public string MedicaidContract { get; set; }
        public Nullable<System.DateTime> MedicaidContractSubmitDate { get; set; }
        public string ReleaseInformation { get; set; }
        public Nullable<System.DateTime> ReleaseInformationSubmitDate { get; set; }
        public string ETR { get; set; }
        public Nullable<System.DateTime> ETRSubmitDate { get; set; }
        public string IEP { get; set; }
        public Nullable<System.DateTime> IEPSubmitDate { get; set; }
        public string C504 { get; set; }
        public Nullable<System.DateTime> C504SubmitDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string DistrictNotifiedSent { get; set; }
        public Nullable<System.DateTime> DistrictNotifiedSentSubmitDate { get; set; }
        public Nullable<int> DistrictNotified { get; set; }
        public string RecordRequestSent { get; set; }
        public string RecordReceived { get; set; }
        public string RecordSent { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
