//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int RoomID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> RoomTypePL { get; set; }
        public Nullable<short> MaxRoomCapacity { get; set; }
        public string RoomNumber { get; set; }
        public string RoomName { get; set; }
        public string Building { get; set; }
        public string House { get; set; }
        public Nullable<bool> RoomStatus { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual PickListDetails_Bak PickListDetails_Bak { get; set; }
        public virtual School School { get; set; }
    }
}
