//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolLunchMenu
    {
        public int SchoolLunchMenuId { get; set; }
        public Nullable<int> Schoolid { get; set; }
        public string MenuAttachmentName { get; set; }
        public string MenuAttachmentType { get; set; }
        public byte[] MenuAttachmentData { get; set; }
        public string MenuAttachmentSize { get; set; }
        public string MenuAttachmentExtension { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
