//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolCourseSectionStaffHistory
    {
        public int SchoolCourseSectionHistoryID { get; set; }
        public Nullable<int> SchoolCourseSectionStaffID { get; set; }
        public Nullable<int> SchoolCourseSectionRoleID { get; set; }
        public Nullable<int> SchoolCourseSectionID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string LegacyStaffID { get; set; }
        public string LegacyCourseSectionID { get; set; }
    
        public virtual SchoolCourseSection SchoolCourseSection { get; set; }
    }
}
