//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolPortal
    {
        public int SchoolPortalID { get; set; }
        public int SchoolID { get; set; }
        public int DistrictPortalID { get; set; }
        public int PortalPL { get; set; }
        public Nullable<bool> PermitStuTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> CanParentUpdate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> ActivateNY { get; set; }
        public Nullable<int> NextSchoolYearPL { get; set; }
    }
}
