//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolTerm
    {
        public SchoolTerm()
        {
            this.SchoolCourseSections = new HashSet<SchoolCourseSection>();
        }
    
        public int SchoolTermID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public int SchoolYearTermTypeID { get; set; }
        public Nullable<int> SchoolYearTermsPL { get; set; }
        public Nullable<int> SchoolYearID { get; set; }
        public Nullable<System.DateTime> TermStartDate { get; set; }
        public Nullable<System.DateTime> TermEndDate { get; set; }
        public Nullable<short> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string LegacySchoolID { get; set; }
        public Nullable<int> TypeOfTermPL { get; set; }
        public string LegacySchoolTermID { get; set; }
    
        public virtual PickListDetails_Bak PickListDetails_Bak { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak1 { get; set; }
        public virtual School School { get; set; }
        public virtual ICollection<SchoolCourseSection> SchoolCourseSections { get; set; }
        public virtual SchoolYearTermType SchoolYearTermType { get; set; }
    }
}
