//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.AttendanceSettings = new HashSet<AttendanceSetting>();
            this.BellSchedules = new HashSet<BellSchedule>();
            this.BuildingAssignments = new HashSet<BuildingAssignment>();
            this.Orientations = new HashSet<Orientation>();
            this.ProgramCodes = new HashSet<ProgramCode>();
            this.Rooms = new HashSet<Room>();
            this.SchoolAttendancePatterns = new HashSet<SchoolAttendancePattern>();
            this.SchoolContacts = new HashSet<SchoolContact>();
            this.SchoolCourses = new HashSet<SchoolCourse>();
            this.SchoolCourseSections = new HashSet<SchoolCourseSection>();
            this.SchoolDays = new HashSet<SchoolDay>();
            this.SchoolEvents = new HashSet<SchoolEvent>();
            this.SchoolGPASetups = new HashSet<SchoolGPASetup>();
            this.SchoolGradeLevels = new HashSet<SchoolGradeLevel>();
            this.SchoolGradeScales = new HashSet<SchoolGradeScale>();
            this.SchoolTerms = new HashSet<SchoolTerm>();
            this.SchoolYears = new HashSet<SchoolYear>();
            this.Staffs = new HashSet<Staff>();
            this.StaffSchoolMappings = new HashSet<StaffSchoolMapping>();
            this.Students = new HashSet<Student>();
            this.StudentApplications = new HashSet<StudentApplication>();
            this.StudentAssessments = new HashSet<StudentAssessment>();
            this.StudentOrientations = new HashSet<StudentOrientation>();
            this.StudentPrograms = new HashSet<StudentProgram>();
            this.StudentSchedules = new HashSet<StudentSchedule>();
            this.Addresses = new HashSet<Address>();
        }
    
        public int SchoolID { get; set; }
        public int DistrictID { get; set; }
        public Nullable<int> AlternateID { get; set; }
        public Nullable<int> PhotoID { get; set; }
        public Nullable<int> LogoID { get; set; }
        public string SchoolIRN { get; set; }
        public string SchoolName { get; set; }
        public string SchooShortlCode { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string SchoolAbbreviation { get; set; }
        public string AlternateSchoolIRN { get; set; }
        public string Grades { get; set; }
        public string HistoricalGrades { get; set; }
        public byte[] SchoolPicture { get; set; }
        public byte[] SchoolLogo { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> ExcludeStateReporting { get; set; }
        public Nullable<bool> Orientation { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> EvolveSchool { get; set; }
        public Nullable<int> OrgTypePL { get; set; }
        public string LegacySchoolID { get; set; }
        public string LegacyDistrictID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public string LoadSource { get; set; }
        public Nullable<int> STG_TableID { get; set; }
        public string LastReportingPeriodComment { get; set; }
        public string RecordseMail { get; set; }
    
        public virtual ICollection<AttendanceSetting> AttendanceSettings { get; set; }
        public virtual ICollection<BellSchedule> BellSchedules { get; set; }
        public virtual ICollection<BuildingAssignment> BuildingAssignments { get; set; }
        public virtual District District { get; set; }
        public virtual ICollection<Orientation> Orientations { get; set; }
        public virtual ICollection<ProgramCode> ProgramCodes { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual ICollection<SchoolAttendancePattern> SchoolAttendancePatterns { get; set; }
        public virtual ICollection<SchoolContact> SchoolContacts { get; set; }
        public virtual ICollection<SchoolCourse> SchoolCourses { get; set; }
        public virtual ICollection<SchoolCourseSection> SchoolCourseSections { get; set; }
        public virtual ICollection<SchoolDay> SchoolDays { get; set; }
        public virtual ICollection<SchoolEvent> SchoolEvents { get; set; }
        public virtual ICollection<SchoolGPASetup> SchoolGPASetups { get; set; }
        public virtual ICollection<SchoolGradeLevel> SchoolGradeLevels { get; set; }
        public virtual ICollection<SchoolGradeScale> SchoolGradeScales { get; set; }
        public virtual ICollection<SchoolTerm> SchoolTerms { get; set; }
        public virtual ICollection<SchoolYear> SchoolYears { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<StaffSchoolMapping> StaffSchoolMappings { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<StudentApplication> StudentApplications { get; set; }
        public virtual ICollection<StudentAssessment> StudentAssessments { get; set; }
        public virtual ICollection<StudentOrientation> StudentOrientations { get; set; }
        public virtual ICollection<StudentProgram> StudentPrograms { get; set; }
        public virtual ICollection<StudentSchedule> StudentSchedules { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
    }
}
