//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionStaffMapping
    {
        public int SectionStaffMappingID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> StaffHQTID { get; set; }
        public int SchoolCourseSectionID { get; set; }
        public Nullable<int> StaffRolePL { get; set; }
        public string StaffProviderIRN { get; set; }
        public string StaffHQTIRN { get; set; }
        public Nullable<System.DateTime> StaffStartDate { get; set; }
        public Nullable<System.DateTime> StaffEndDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual PickListDetails_Bak PickListDetails_Bak { get; set; }
        public virtual SchoolCourseSection SchoolCourseSection { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
