//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionStaff
    {
        public int SectionStaffId { get; set; }
        public int SectionId { get; set; }
        public int StaffRoleId { get; set; }
        public string StaffHQTIRN { get; set; }
        public string StaffProviderIRN { get; set; }
        public System.DateTime StaffStartDate { get; set; }
        public Nullable<System.DateTime> StaffEndDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
