//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffSchoolDepartment
    {
        public int StaffSchoolDepartmentID { get; set; }
        public Nullable<int> StaffSchoolMappingID { get; set; }
        public Nullable<int> DepartmentPL { get; set; }
        public Nullable<int> PrimaryDepartmentHead { get; set; }
        public Nullable<int> SecondaryDepartmentHead { get; set; }
        public string Description { get; set; }
        public Nullable<bool> ActiveStatus { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
