//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffDistrictMapping
    {
        public int StaffDistrictMappingID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> HQTPL { get; set; }
        public string HQTSchoolIRN { get; set; }
        public string HQTDistrictIRN { get; set; }
        public string HQTAlternateIRN { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> Default { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> stgid { get; set; }
        public string legacyschoolid { get; set; }
        public string defaultschoolid { get; set; }
        public string legacydistrictid { get; set; }
    
        public virtual District District { get; set; }
    }
}
