//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standard
    {
        public int StandardID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public int OrganizationID { get; set; }
        public Nullable<int> OriginalStandardID { get; set; }
        public int PickListID_StateID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<short> GradeLevelID { get; set; }
        public Nullable<short> Alternategrade { get; set; }
        public Nullable<short> SortOrder { get; set; }
        public string Subject { get; set; }
        public string AlternateSubject { get; set; }
        public string DocumentCode { get; set; }
        public string Status { get; set; }
        public string DocumentType { get; set; }
        public string DocumentTitle { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
