//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.GiftedStudentsInfoes = new HashSet<GiftedStudentsInfo>();
            this.ProgramCodes = new HashSet<ProgramCode>();
            this.RequiredDocuments = new HashSet<RequiredDocument>();
            this.StudentAccommodations = new HashSet<StudentAccommodation>();
            this.StudentAlerts = new HashSet<StudentAlert>();
            this.StudentAssessments = new HashSet<StudentAssessment>();
            this.StudentAssessmentAccommodations = new HashSet<StudentAssessmentAccommodation>();
            this.StudentAttendances = new HashSet<StudentAttendance>();
            this.StudentCourseRequests = new HashSet<StudentCourseRequest>();
            this.StudentExcessiveHabitualAbs = new HashSet<StudentExcessiveHabitualAb>();
            this.StudentGPAs = new HashSet<StudentGPA>();
            this.studentgrades = new HashSet<studentgrade>();
            this.StudentNextYears = new HashSet<StudentNextYear>();
            this.StudentOrientations = new HashSet<StudentOrientation>();
            this.StudentPrograms = new HashSet<StudentProgram>();
            this.StudentSchedules = new HashSet<StudentSchedule>();
            this.StudentStandingRecords = new HashSet<StudentStandingRecord>();
            this.StudentTransferOfRights = new HashSet<StudentTransferOfRight>();
            this.Addresses = new HashSet<Address>();
        }
    
        public int StudentID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> CounselorID { get; set; }
        public Nullable<int> StudentApplicationID { get; set; }
        public int PersonID { get; set; }
        public Nullable<int> GradeLevelPL { get; set; }
        public Nullable<int> StateGradeLevelPL { get; set; }
        public Nullable<int> StateGradeLevelNext { get; set; }
        public string BirthPlaceCity { get; set; }
        public Nullable<int> NativeLanguagePL { get; set; }
        public Nullable<int> HomeLanuagePL { get; set; }
        public Nullable<int> HomeLessPL { get; set; }
        public string MothersMaidentName { get; set; }
        public Nullable<bool> Gifted { get; set; }
        public Nullable<bool> GIEP { get; set; }
        public Nullable<bool> Migrant { get; set; }
        public Nullable<System.DateTime> GradeNinthEnteredYear { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Password { get; set; }
        public Nullable<int> PickListCategoryID { get; set; }
        public string LegacyStudentID { get; set; }
        public string LegacySchool { get; set; }
        public string LegacyStaffID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> AttendancePattern { get; set; }
        public Nullable<int> LastGradeCompleted { get; set; }
        public string SSID { get; set; }
        public Nullable<int> DisadvantagementPL { get; set; }
        public Nullable<int> PreschoolPovertyPL { get; set; }
        public Nullable<int> LimitedEnglishProficiencyPL { get; set; }
        public Nullable<int> RetainedStatusPL { get; set; }
        public Nullable<int> ImmigrantStatusPL { get; set; }
        public Nullable<int> UnaccompaniedYouthPL { get; set; }
        public Nullable<int> PreviousDistrictID { get; set; }
        public Nullable<int> AccountabilitySchoolID { get; set; }
        public Nullable<int> AttendingBuildingIRN { get; set; }
        public Nullable<int> MajorityAttendanceSchoolID { get; set; }
        public Nullable<int> FYEnteredNinthGrade { get; set; }
        public Nullable<int> STG_Student_ID { get; set; }
        public string ExternalUserName { get; set; }
        public string ExternalPassword { get; set; }
        public Nullable<int> ServiceLevelPL { get; set; }
        public Nullable<int> Region { get; set; }
        public string Email { get; set; }
        public Nullable<int> GradReqID { get; set; }
        public Nullable<int> MilitaryPL { get; set; }
        public string SchoolAssignedEmail { get; set; }
    
        public virtual ICollection<GiftedStudentsInfo> GiftedStudentsInfoes { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak1 { get; set; }
        public virtual ICollection<ProgramCode> ProgramCodes { get; set; }
        public virtual ICollection<RequiredDocument> RequiredDocuments { get; set; }
        public virtual School School { get; set; }
        public virtual ICollection<StudentAccommodation> StudentAccommodations { get; set; }
        public virtual ICollection<StudentAlert> StudentAlerts { get; set; }
        public virtual ICollection<StudentAssessment> StudentAssessments { get; set; }
        public virtual ICollection<StudentAssessmentAccommodation> StudentAssessmentAccommodations { get; set; }
        public virtual ICollection<StudentAttendance> StudentAttendances { get; set; }
        public virtual ICollection<StudentCourseRequest> StudentCourseRequests { get; set; }
        public virtual ICollection<StudentExcessiveHabitualAb> StudentExcessiveHabitualAbs { get; set; }
        public virtual ICollection<StudentGPA> StudentGPAs { get; set; }
        public virtual ICollection<studentgrade> studentgrades { get; set; }
        public virtual ICollection<StudentNextYear> StudentNextYears { get; set; }
        public virtual ICollection<StudentOrientation> StudentOrientations { get; set; }
        public virtual ICollection<StudentProgram> StudentPrograms { get; set; }
        public virtual ICollection<StudentSchedule> StudentSchedules { get; set; }
        public virtual ICollection<StudentStandingRecord> StudentStandingRecords { get; set; }
        public virtual ICollection<StudentTransferOfRight> StudentTransferOfRights { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
    }
}
