//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRequiredDocument
    {
        public int RequiredDocumentRecordId { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> SchoolRequestSentTo { get; set; }
        public Nullable<int> SchoolRequestReceivedFrom { get; set; }
        public string Immunizations { get; set; }
        public string Custody { get; set; }
        public string BirthCertification { get; set; }
        public string LastGradeCard { get; set; }
        public string ProofofResidence { get; set; }
        public string Transcript { get; set; }
        public string TestingOGT { get; set; }
        public string TestingOAA { get; set; }
        public string TestingARCC { get; set; }
        public string TestingACT { get; set; }
        public string PublicityPolicy { get; set; }
        public string EmergencyMedical { get; set; }
        public string EnrollmentPolicy { get; set; }
        public string FinancialResponsibilityPolicy { get; set; }
        public string AcceptableUsePolicy { get; set; }
        public string StudentorParentContract { get; set; }
        public string Title1IncomeInformation { get; set; }
        public string ReleaseofInformation { get; set; }
        public string ETR { get; set; }
        public string MedicaidContract { get; set; }
        public string IEP { get; set; }
        public string C504 { get; set; }
        public Nullable<System.DateTime> TranscriptSubmitDate { get; set; }
        public Nullable<System.DateTime> TestingOGTSubmitDate { get; set; }
        public Nullable<System.DateTime> TestingOAASubmitDate { get; set; }
        public Nullable<System.DateTime> TestingARCCSubmitDate { get; set; }
        public Nullable<System.DateTime> TestingACTSubmitDate { get; set; }
        public Nullable<System.DateTime> RecordRequestSentDate { get; set; }
        public Nullable<System.DateTime> BirthCertificateSubmitDate { get; set; }
        public Nullable<System.DateTime> ProofofResidenceSubmitDate { get; set; }
        public Nullable<System.DateTime> ImmunizationsSubmitDate { get; set; }
        public Nullable<System.DateTime> CustodySubmitDate { get; set; }
        public Nullable<System.DateTime> LastGradeCardSubmitDate { get; set; }
        public Nullable<System.DateTime> RecordRequestReceivedDate { get; set; }
        public Nullable<System.DateTime> EmergencyMedicalSubmitDate { get; set; }
        public Nullable<System.DateTime> EnrollmentPolicySubmitDate { get; set; }
        public Nullable<System.DateTime> FinancialResponsibilityPolicySubmitDate { get; set; }
        public Nullable<System.DateTime> AcceptableUsePolicySubmitDate { get; set; }
        public Nullable<System.DateTime> PublicityPolicySubmitDate { get; set; }
        public Nullable<System.DateTime> StudentorParentContractSubmitDate { get; set; }
        public Nullable<System.DateTime> Title1IncomeInformationSubmitDate { get; set; }
        public Nullable<System.DateTime> MedicaidContractSubmitDate { get; set; }
        public Nullable<System.DateTime> ReleaseofInformationSubmitDate { get; set; }
        public Nullable<System.DateTime> ETRSubmitDate { get; set; }
        public Nullable<System.DateTime> IEPSubmitDate { get; set; }
        public Nullable<System.DateTime> C504SubmitDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
