//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentApplication
    {
        public StudentApplication()
        {
            this.StudentApplicationPhones = new HashSet<StudentApplicationPhone>();
        }
    
        public int StudentApplicationID { get; set; }
        public Nullable<bool> EnriollmentOfficerID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string MailingStreetNumber { get; set; }
        public string MailingStreetName { get; set; }
        public string MailingCity { get; set; }
        public string MailingState { get; set; }
        public string MailingCountry { get; set; }
        public string MailingCounty { get; set; }
        public string MailingNeighbourhood { get; set; }
        public string MailingZipCode { get; set; }
        public Nullable<int> PriorStudentID { get; set; }
        public Nullable<int> GenderPL { get; set; }
        public Nullable<int> SuffixPL { get; set; }
        public Nullable<int> HomePhoneNumTypePL { get; set; }
        public string FormerSchoolTypePL { get; set; }
        public Nullable<int> FirstLanguageTalkPL { get; set; }
        public Nullable<int> AltPhoneNumTypePL { get; set; }
        public Nullable<int> LanguageMostOftenSpokenAtHomePL { get; set; }
        public Nullable<int> LanguageSpokenAtTheStudentsHomePL { get; set; }
        public Nullable<int> HomeLessTypePL { get; set; }
        public string SchoolIRN { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string NickName { get; set; }
        public string MothersMaidenName { get; set; }
        public string HomePhoneNumber { get; set; }
        public string AlternatePhoneNumber { get; set; }
        public System.DateTime DOB { get; set; }
        public string IsHispanic { get; set; }
        public Nullable<bool> MailingAddressSameAsHomeAddress { get; set; }
        public Nullable<int> SchoolDistrictOfResidence { get; set; }
        public Nullable<bool> CurrentlyEnrolledInSchool { get; set; }
        public Nullable<short> FormerSchoolAttendedState { get; set; }
        public string FormerSchoolAttendedCity { get; set; }
        public Nullable<int> FormerSchoolDistrict { get; set; }
        public Nullable<int> FormerSchoolAttended { get; set; }
        public Nullable<int> LastGradeStudentCompleted { get; set; }
        public Nullable<int> GradeLevelEntering { get; set; }
        public Nullable<bool> TestedGiftedorTalented { get; set; }
        public Nullable<bool> HasGIEP { get; set; }
        public Nullable<bool> EvaluatingDisablity { get; set; }
        public Nullable<bool> IsDisabledUnderSection { get; set; }
        public Nullable<bool> Expulsion { get; set; }
        public string ExpulsionExplanation { get; set; }
        public Nullable<int> StudentLEPPreviousSchool { get; set; }
        public Nullable<short> IsSpeakingWrtingUnderstandingEnglish { get; set; }
        public Nullable<System.DateTime> FirstAttendedSchoolYear { get; set; }
        public Nullable<bool> DoesStudentNeedPCPackage { get; set; }
        public Nullable<bool> DoesStudentNeedPrinter { get; set; }
        public Nullable<bool> CurrentlyInternetServiceAtHome { get; set; }
        public Nullable<int> CurrentInternetServiceType { get; set; }
        public string AboutTreca { get; set; }
        public string ReasonForSelectingTreca { get; set; }
        public string EverAttendedTreca { get; set; }
        public string DateStudentEnterNinthGrade { get; set; }
        public Nullable<bool> IsMigrantOrFormWorker { get; set; }
        public Nullable<bool> IsLackOfRegularNightTimeResidence { get; set; }
        public int ApprovalStatus { get; set; }
        public Nullable<System.DateTime> OriginalOrientationDate { get; set; }
        public Nullable<bool> Validate { get; set; }
        public Nullable<bool> DoNotDelete { get; set; }
        public string Notes { get; set; }
        public Nullable<short> FormFillStatus { get; set; }
        public string District { get; set; }
        public Nullable<bool> HPrivate { get; set; }
        public Nullable<bool> HALTPrivate { get; set; }
        public string AGE { get; set; }
        public Nullable<bool> RaceCheckAllThatApply1 { get; set; }
        public Nullable<bool> RaceCheckAllThatApply2 { get; set; }
        public Nullable<bool> RaceCheckAllThatApply3 { get; set; }
        public Nullable<bool> RaceCheckAllThatApply4 { get; set; }
        public Nullable<bool> RaceCheckAllThatApply5 { get; set; }
        public string RegistrationNumber { get; set; }
        public string ReasonNotEnrolledPreviously { get; set; }
        public string FilePath { get; set; }
        public string BirthPlaceCity { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string MailingApartment { get; set; }
        public string MailingLot { get; set; }
        public string MailingOther { get; set; }
        public Nullable<int> MilitaryPL { get; set; }
    
        public virtual PickListDetails_Bak PickListDetails_Bak { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak1 { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak2 { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak3 { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak4 { get; set; }
        public virtual School School { get; set; }
        public virtual ICollection<StudentApplicationPhone> StudentApplicationPhones { get; set; }
    }
}
