//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAccommodation
    {
        public int StudentAccommodationID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public int AccomodationID { get; set; }
        public Nullable<bool> ReadingDiasbility { get; set; }
        public Nullable<bool> WritingDiasbility { get; set; }
        public Nullable<bool> MathematicalDisability { get; set; }
        public Nullable<bool> CommunicationDisorder { get; set; }
        public Nullable<bool> S { get; set; }
        public Nullable<bool> All { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Accommodation Accommodation { get; set; }
        public virtual Student Student { get; set; }
    }
}
