//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentNextYear_06152016
    {
        public int StudentNextYearID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> NextGradeLevelPL { get; set; }
        public Nullable<int> NextStateGradeLevelPL { get; set; }
        public Nullable<int> NextHomeroomID { get; set; }
        public Nullable<int> NextAttendancePatternID { get; set; }
        public Nullable<int> NextSchoolID { get; set; }
        public Nullable<bool> ReturningYN { get; set; }
    }
}
