//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentOrientation
    {
        public StudentOrientation()
        {
            this.StudentOrientationSchedules = new HashSet<StudentOrientationSchedule>();
        }
    
        public int StudentOrientationID { get; set; }
        public int SchoolID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> OrientationScheduleID { get; set; }
        public Nullable<int> OrientationStatusPL { get; set; }
        public Nullable<int> OrientationTypePL { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> StudentApplicationID { get; set; }
    
        public virtual PickListDetails_Bak PickListDetails_Bak { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak1 { get; set; }
        public virtual School School { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<StudentOrientationSchedule> StudentOrientationSchedules { get; set; }
    }
}
