//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentProgram
    {
        public StudentProgram()
        {
            this.StudentProgramHistories = new HashSet<StudentProgramHistory>();
        }
    
        public int StudentProgramID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> CalendarID { get; set; }
        public Nullable<int> ProgramTypePL { get; set; }
        public Nullable<int> ProgramProviderIRN { get; set; }
        public Nullable<decimal> AmountOfTime { get; set; }
        public string Company { get; set; }
        public string Therapist { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual PickListDetails_Bak PickListDetails_Bak { get; set; }
        public virtual School School { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<StudentProgramHistory> StudentProgramHistories { get; set; }
    }
}
