//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentScheduleBack
    {
        public int StudentScheduleId { get; set; }
        public int StudentId { get; set; }
        public int SchoolId { get; set; }
        public int SchoolYearId { get; set; }
        public int SchoolCourseSectionId { get; set; }
        public string Status { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string LegacyStudentID { get; set; }
        public string LegacySchoolID { get; set; }
        public string LegacyCourseID { get; set; }
        public string LegacySectionNumber { get; set; }
        public string LegacyCourseSectionID { get; set; }
        public Nullable<int> StudentCourseStatusPL { get; set; }
    }
}
