//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentStandingRecord
    {
        public int StudentStandingRecordID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> TuitionStatusPL { get; set; }
        public string PercentOfTime { get; set; }
        public Nullable<System.DateTime> DistrictAdmissionDate { get; set; }
        public Nullable<int> AssignedSchoolID { get; set; }
        public Nullable<int> HowReceivedCodePL { get; set; }
        public Nullable<int> HowReceivedSchoolID { get; set; }
        public Nullable<int> SentToDistrictReason1PL { get; set; }
        public Nullable<int> SentToDistrictIRN1 { get; set; }
        public string PercentofTime1 { get; set; }
        public Nullable<int> SentToDistrictReason2PL { get; set; }
        public Nullable<int> SentToDistrictIRN2 { get; set; }
        public string PercentofTime2 { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> NextSchoolID { get; set; }
    
        public virtual PickListDetails_Bak PickListDetails_Bak { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak1 { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak2 { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak3 { get; set; }
        public virtual Student Student { get; set; }
    }
}
