//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentProgramHistory
    {
        public int StudentProgramHistoryID { get; set; }
        public Nullable<int> StudentProgramID { get; set; }
        public Nullable<System.DateTime> ProgramStartDate { get; set; }
        public Nullable<System.DateTime> ProgramEndDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual StudentProgram StudentProgram { get; set; }
    }
}
