//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentGraduation
    {
        public int StudentGraduationID { get; set; }
        public int StudentID { get; set; }
        public int PickListCategoryID { get; set; }
        public Nullable<int> SSID { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> SchoolIRN { get; set; }
        public string DiplomaName { get; set; }
        public string PickListID_DiplomaType { get; set; }
        public string OGTAlternativeElement { get; set; }
        public string CORE_EconomicalFinancialLiteratureMet { get; set; }
        public string COREArtsRequirementMet { get; set; }
        public string ExemptedPhysicalEducationGradationRequirement { get; set; }
        public string IEPEducationElement { get; set; }
        public string CTEElement { get; set; }
        public string COREGraduationExemptedCode { get; set; }
        public string MilitaryCompactGraduationAlternateCount { get; set; }
        public string COREGraduationRequirementsMet { get; set; }
        public Nullable<System.DateTime> DiplomaDate { get; set; }
        public Nullable<System.DateTime> COREGraduationExemptedDate { get; set; }
        public Nullable<System.DateTime> GraduationExpectedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
