//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentgrade0406
    {
        public int StudentGradeId { get; set; }
        public int StudentId { get; set; }
        public Nullable<int> StudentGradeLevelId { get; set; }
        public int SubjectAreaForCreditId { get; set; }
        public Nullable<int> FinalGradePercentage { get; set; }
        public string CourseNumber { get; set; }
        public string CourseName { get; set; }
        public string SectionNumber { get; set; }
        public string TermName { get; set; }
        public string FinalGradeAlpha { get; set; }
        public string DistrictName { get; set; }
        public string SchoolName { get; set; }
        public string SchoolYear { get; set; }
        public string TeacherName { get; set; }
        public Nullable<decimal> CreditAttempted { get; set; }
        public Nullable<decimal> CreditEarned { get; set; }
        public Nullable<bool> isHistorical { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string LegacyStudentID { get; set; }
        public string Source { get; set; }
        public Nullable<int> STG_ExternalGrades_ID { get; set; }
        public string LegacyAcademy { get; set; }
    }
}
