//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentETR
    {
        public int StudentsETRID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> ETROutcomePL { get; set; }
        public Nullable<int> ETRFundingCodeTypePL { get; set; }
        public Nullable<int> ETRNonCompliancePL { get; set; }
        public Nullable<int> ETRDisabilityConditionPL { get; set; }
        public Nullable<int> ETREventTypePL { get; set; }
        public Nullable<int> SpecialEducationTypePL { get; set; }
        public Nullable<System.DateTime> ETROutcomeBeginDate { get; set; }
        public Nullable<System.DateTime> ETROutcomeEndDate { get; set; }
        public Nullable<System.DateTime> ETREventDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ETROutcomeTypePL { get; set; }
        public string LegacyStudentID { get; set; }
        public string LegacySchoolID { get; set; }
        public string DocumentExtension { get; set; }
        public string DocumentSize { get; set; }
        public string DocumentType { get; set; }
        public string DocumentName { get; set; }
        public byte[] DocumentData { get; set; }
    
        public virtual PickListDetails_Bak PickListDetails_Bak { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak1 { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak2 { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak3 { get; set; }
        public virtual PickListDetails_Bak PickListDetails_Bak4 { get; set; }
    }
}
