//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDA_BrightspaceProgress
    {
        public int TDA_BrightspaceProgressID { get; set; }
        public string StudentID { get; set; }
        public string BSCourseCode { get; set; }
        public string Groups { get; set; }
        public Nullable<int> PointsEarned { get; set; }
        public Nullable<int> PointsTotal { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
