//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDAStudentActivityTime
    {
        public int StudentID { get; set; }
        public string ActivityType { get; set; }
        public string ActivityName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int TotalMinutes { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string SchoolYear { get; set; }
    }
}
