//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestingRoster
    {
        public int TestingRosterID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Duration { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<bool> Attended { get; set; }
        public Nullable<bool> Contactded { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
