//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_SCA
    {
        public int STG_AddressID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CountyPL { get; set; }
        public string StatePL { get; set; }
        public string CountryPL { get; set; }
        public string Apartment { get; set; }
        public string Lot { get; set; }
        public string Other { get; set; }
        public string Neighborhood { get; set; }
        public string LookupValue { get; set; }
    }
}
