//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int VehicleID { get; set; }
        public int PickListCategoryID { get; set; }
        public int SchoolID { get; set; }
        public Nullable<int> TotalSeats { get; set; }
        public Nullable<int> AvailableSeats { get; set; }
        public string VehicleNbr { get; set; }
        public string VehicleOwnerShipType { get; set; }
        public string IsActive { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifedDate { get; set; }
    }
}
