//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Withdrawal
    {
        public int WithdrawlID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> WithdrawlCodePL { get; set; }
        public Nullable<int> PlansToAttendDistrict { get; set; }
        public Nullable<int> DiplomaType { get; set; }
        public string WithdrawlDescription { get; set; }
        public Nullable<int> GraduationYear { get; set; }
        public Nullable<System.DateTime> WithdrawlDate { get; set; }
        public Nullable<System.DateTime> DIplomaDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string LegacyStudentID { get; set; }
        public string LegacyPlansToAttendDistrictID { get; set; }
        public Nullable<int> STG_Withdrawals_ID { get; set; }
        public Nullable<int> WithdrawalSchoolID { get; set; }
        public Nullable<System.DateTime> DateCoursesCompleted { get; set; }
        public Nullable<int> DistrictCoursesCompleted { get; set; }
    
        public virtual PickListDetails_Bak PickListDetails_Bak { get; set; }
    }
}
